### PR TITLE
Upgrade to bevy 0.15

### PR DESCRIPTION
**Pull request by cBournhonesque**
Some remaining bugs:
- when a client closes the window, the connection is not spontaneously ended on the server side. Only intentional disconnections seem to be handled. This is a regression

Status:
- [x] leafwing upgraded

Examples
- auth:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- avian_3d_character:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- avian_physics:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
    - (non-blocking, but the local client's updates are jittery for other clients)
  - [x] client-and-server
  - [x] client wasm
- bullet_prepawn:
  - [X] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- client_replication:
  - [X] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- distribution_authority:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [ ] host-server
    - ball doesn't move
  - [x] client-and-server
  - [x] client wasm
- interest_management:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- lobby:
  - [x] server
  - [x] client
    - the games hosted by the dedicated server seem to work, but the games hosted by the client acting as host-server don't show any entities on the screen, not sure why

- priority:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- replication_groups:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- simple_box:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- simple_setup:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm
- spaceships:
  - [x] server without gui
  - [x] client
  - [x] server with gui
  - [x] host-server
  - [x] client-and-server
  - [x] client wasm

TODO:
- upgrade avian
- test examples

### CODE REVIEW

**Comment by simbleau** [comment]
Status?

**Comment by cBournhonesque** [comment]
Need to wait for leafwing/avian to upgrade

**Comment by SK83RJOSH** [comment]
Just waiting on Avian now by the way, they're on 0.15, but haven't published a new version in a while. 🙂

**Comment by Seldom-SE** [comment]
`cargo b --target wasm32-unknown-unknown` is failing with
```
error[E0560]: struct `WebKeepalivePlugin` has no field named `initial_wake_delay`
  --> lightyear/src/client/web.rs:26:13
   |
26 |             initial_wake_delay: 1000.0,
   |             ^^^^^^^^^^^^^^^^^^ `WebKeepalivePlugin` does not have this field
   |
   = note: available fields are: `wake_delay`
```
for me

**Comment by Jieiku** [comment]
Avian just released: https://github.com/Jondolf/avian/releases/tag/v0.2.0

so hopefully nothing holding this back now :)

**Comment by RJ** [comment]
I think we should remove `FixedSet::{Main, Physics}` in the examples now, and ensure we're using `FixedPostUpdate` for avian plugins (the default). then we can just put our system in `FixedUpdate` without ordering concerns.

made a start in #735

**Pull request merged**
