### PR TITLE
chore(docs): add sequence diagrams to book

### PR DESCRIPTION
**Pull request by mikeder**
For my own education, I figured I'd try to draw out the client replication sequences.

If you find these accurate and helpful, I'd be happy to draw up more for the other topics as I come to understand them.

### CODE REVIEW

**Comment by cBournhonesque** [comment]
I tried visualizing your diagrams but nothing shows up for me when i `mdbook serve`; how did you test this?

**Comment by mikeder** [comment]
I used a Mermaid plugin in VSCode originally, I can try `mdbook serve` to see if something needs tweaking to work there.

**Comment by mikeder** [comment]
FWIW they render in GitHub if you change to the rich diff view but I'll try the `mdbook` method.
Screenshot 2024-05-04 at 10 45 51 AM

**Comment by msvbg** [comment]
You would likely need something like https://github.com/badboy/mdbook-mermaid to make it work in mdbook. Or you could just render the diagrams to images and include them

**Comment by cBournhonesque** [comment]
Yes i have `mdbook-mermaid v0.13.0` but it doesn't show anything for me; even though it does show the diagram in here: https://cbournhonesque.github.io/lightyear/book/concepts/bevy_integration/system_order.html

Maybe this version doesn't support the diagrams or something?

**Comment by cBournhonesque** [comment]
I was able to view them using the rich diff feature of github, the diagrams are amazing! I should have way more of these kinds of sequence diagrams.
I might tweak them a bit later to clarify what is being replicated (the `Replicate` on the arrow can make it sound that the Replicate component is being networked), but overall I think it's a great addition

**Pull request merged**
